version: '3.7'

services:
    wildfly:
      image: 10.50.23.30:5000/wildfly-scouter-dashboard:latest ### Edit image name 
      build:
        context: .
        dockerfile: Dockerfile
#      restart: always # if container down restart autometic
      user: "701"
      ports:
        - 8080:8080 ### Edit port name (http) 
        - 8009:8009 ### Edit port name (ajp)
        - 9990:9990 ### Edit port name (webadmin)
      deploy:
        mode: replicated
        replicas: 1
        placement:
           constraints: [node.role == manager]
#           constraints: [node.role == worker]

      volumes:
        - /box/logs/wildfly/vms:/opt/jboss/wildfly/standalone/log ### Edit WAS name 
#      networks:
#        - backend
      environment:
        WAS_NAME: vms ### Edit WAS name 
        TZ: Asia/Seoul

